name: learn_code
description: A new Flutter project.
publish_to: 'none' # 'flutter pub publish' komutunun yanlışlıkla çalışmasını engeller.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Uygulamanın çalışması için gerekli olan paketler
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Paketler okunabilirliği artırmak için alfabetik olarak sıralandı
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.0
  intl: ^0.20.2
  lottie: ^3.1.0

# Sadece geliştirme ve test aşamasında gerekli olan paketler
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# Flutter'a özel yapılandırmalar
flutter:
  uses-material-design: true

  # Kendi manuel çeviri betiğinizi kullandığınız için Flutter'ın otomatik
  # çeviri aracı kapatılmıştır. Bu satırı kaldırmak önemlidir!
  # generate: true # <--- BU SATIR KALDIRILDI

  # Projeye dahil edilen varlık (asset) dosyaları
  assets:
    - .env
    - assets/logos/
    - assets/animations/